apiVersion: v1
kind: Service
metadata:
  name: erp-api-service-qa
  namespace: qa
  labels:
    app: erp-api
    environment: qa
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: erp-api
    environment: qa
